{ ... }:
{
  imports = [
    ./accounts.nix
    ./aerospace.nix
    ./ai.nix
    ./alacritty.nix
    ./bat.nix
    ./cargo.nix
    ./cmus.nix
    ./fish.nix
    ./ghostty.nix
    ./git.nix
    ./helix.nix
    ./home-manager.nix
    ./iamb.nix
    ./jujutsu.nix
    ./kanata.nix
    ./karabiner.nix
    ./librewolf.nix
    ./mvp.nix
    ./musicbrainz-picard.nix
    ./nh.nix
    ./niri.nix
    ./niri-session-manager.nix
    ./nix.nix
    ./noctalia.nix
    ./osx-scrobbler.nix
    # ./reaper.nix
    ./rofi.nix
    ./sioyek.nix
    ./ssh.nix
    ./taskwarrior.nix
    ./theme-switch.nix
    ./tofi.nix
    ./wezterm.nix
    ./yazi.nix
    ./zathura.nix
    ./zellij.nix
  ];
}
