[buildPlans.IosevkaOdilf]
family = "Iosevka Odilf"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaOdilf.variants]
  inherits = "ss17"

    [buildPlans.IosevkaOdilf.variants.design]
    one = "no-base"
    two = "straight-neck-serifed"
    three = "flat-top-serifless"
    four = "open-serifed"
    five = "oblique-arched-serifless"
    six = "closed-contour"
    seven = "curly-serifed-crossbar"
    eight = "two-circles"
    nine = "closed-contour"
    zero = "broken-reverse-slash"
    capital-a = "straight-serifless"
    capital-b = "standard-unilateral-serifed"
    capital-c = "unilateral-inward-serifed"
    capital-d = "standard-unilateral-serifed"
    capital-e = "top-left-serifed"
    capital-f = "top-left-serifed"
    capital-g = "toothless-corner-serifless-hooked"
    capital-h = "top-left-serifed"
    capital-i = "serifed"
    capital-j = "descending-serifed-symmetric"
    capital-k = "straight-top-left-and-bottom-right-serifed"
    capital-l = "serifless"
    capital-m = "hanging-motion-serifed"
    capital-n = "standard-motion-serifed"
    capital-p = "closed-motion-serifed"
    capital-q = "detached-bend-tailed"
    capital-r = "straight-top-left-serifed"
    capital-s = "unilateral-inward-serifed"
    capital-t = "motion-serifed"
    capital-u = "toothed-bottom-right-serifed"
    capital-v = "straight-motion-serifed"
    capital-w = "straight-motion-serifed"
    capital-x = "straight-unilateral-motion-serifed"
    capital-y = "straight-motion-serifed"
    capital-z = "cursive-with-horizontal-crossbar"
    a = "double-storey-tailed"
    b = "toothed-motion-serifed"
    c = "unilateral-inward-serifed"
    d = "toothed-bottom-serifed"
    e = "flat-crossbar"
    f = "flat-hook-tailed-crossbar-at-x-height"
    g = "double-storey-open"
    h = "straight-top-left-serifed"
    i = "tailed-serifed"
    j = "flat-hook-serifed"
    k = "straight-top-left-serifed"
    l = "serifed-flat-tailed"
    m = "top-left-serifed"
    n = "straight-top-left-serifed"
    p = "eared-motion-serifed"
    q = "straight-motion-serifed"
    r = "compact-top-serifed"
    s = "serifless"
    t = "bent-hook-asymmetric"
    u = "toothless-corner-motion-serifed"
    v = "straight-motion-serifed"
    w = "straight-motion-serifed"
    x = "straight-unilateral-motion-serifed"
    y = "straight-motion-serifed"
    z = "straight-serifless-with-horizontal-crossbar"
    tilde = "low"
    asterisk = "penta-low"
    underscore = "low"
    caret = "low"
    ascii-single-quote = "raised-comma"
    paren = "large-contour"
    brace = "curly-flat-boundary"
    guillemet = "curly"
    ampersand = "closed"
    dollar = "slanted-open"
    cent = "slanted-open"
    percent = "dots"
    bar = "force-upright"
    question = "corner"
    micro-sign = "toothed-motion-serifed"
    lig-ltgteq = "slanted"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "without-notch"
